In [1]:
import torch
import numpy as np

# 四则运算 add,sub,mul,div

In [2]:
tensor = torch.randint(0,10,size=(2,3))
print(tensor+10) #不修改原数据
print(tensor)

tensor([[16, 19, 10],
        [11, 11, 14]])
tensor([[6, 9, 0],
        [1, 1, 4]])


In [10]:
tensor = torch.randint(0,10,size=(2,3))
print(tensor.add(10)) #不修改原数据
print(tensor)

tensor([[14, 16, 15],
        [19, 12, 15]])
tensor([[4, 6, 5],
        [9, 2, 5]])


In [13]:
tensor = torch.randint(0,10,size=(2,3))
print(tensor.add_(10)) # 修改原数据
print(tensor)

tensor([[18, 15, 15],
        [10, 13, 13]])
tensor([[18, 15, 15],
        [10, 13, 13]])


In [14]:
# neg
tensor = torch.randint(0,10,size=(2,3))
print(tensor.neg()) #或者neg_
print(tensor)

tensor([[-1, -1, -9],
        [-3, -9, -7]])
tensor([[1, 1, 9],
        [3, 9, 7]])


In [15]:
# **
tensor = torch.randint(0,10,size=(2,3))
print(tensor**2)
print(tensor)

tensor([[ 4, 16, 49],
        [81,  9, 16]])
tensor([[2, 4, 7],
        [9, 3, 4]])


In [16]:
# pow pow_
tensor = torch.randint(0,10,size=(2,3))
print(tensor.pow(2))
print(tensor)
print(tensor.pow_(2))
print(tensor)


tensor([[25, 16, 36],
        [ 4, 81, 49]])
tensor([[5, 4, 6],
        [2, 9, 7]])
tensor([[25, 16, 36],
        [ 4, 81, 49]])
tensor([[25, 16, 36],
        [ 4, 81, 49]])


In [26]:
# sqrt sqrt_
tensor = torch.tensor([4,9,16,25])
print(tensor.sqrt())
print(tensor)

tensor = tensor.double()
print(tensor.double().sqrt_())
print(tensor)


tensor([2., 3., 4., 5.])
tensor([ 4,  9, 16, 25])
tensor([2., 3., 4., 5.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)


In [29]:
# exp exp_
tensor = torch.tensor([1.0,2,3,4])
print(tensor.exp())
print(tensor)

print(tensor.exp_())
print(tensor)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
tensor([1., 2., 3., 4.])
tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
tensor([ 2.7183,  7.3891, 20.0855, 54.5981])


In [ ]:
# log log_ 以e为底

# 元素级乘法

In [30]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
print(tensor*tensor)

tensor([[ 1,  4,  9],
        [16, 25, 36]])


# 矩阵乘法

In [32]:
# 二维
tensor1 = torch.tensor([[1,2,4],[3,4,6]])
tensor2 = torch.tensor([[1,2],[3,4],[5,6]])
print(tensor1 @ tensor2)
print(torch.matmul(tensor1,tensor2))
print(torch.mm(tensor1,tensor2))


tensor([[27, 34],
        [45, 58]])
tensor([[27, 34],
        [45, 58]])
tensor([[27, 34],
        [45, 58]])


In [33]:
# 三维张量乘法
tensor1 = torch.tensor([[[1,2,4],[3,4,6]],[[1,2,4],[3,4,6]]])
tensor2 = torch.tensor([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(tensor1 @ tensor2)

tensor([[[27, 34],
         [45, 58]],

        [[27, 34],
         [45, 58]]])


In [3]:
# sum()
tensor = torch.tensor([[1,2,3],[4,5,6]])
print(tensor.sum())

# sum(dim)
print(tensor.sum(dim=0))  # 对第0维求和(列)
print(tensor.sum(dim=1))  # 对第1维求和(行)


tensor(21)
tensor([5, 7, 9])
tensor([ 6, 15])
