In [1]:
import torch
import numpy as np

# 转换张量

# 类型转换

In [6]:
tensor1 = torch.tensor([[1,2],[2,3],[3,4]])
print(tensor1.dtype)

tensor1 = tensor1.half()
print(tensor1.dtype)

tensor1 = tensor1.type(torch.float32)
print(tensor1.dtype)

tensor1 = tensor1.double()
print(tensor1.dtype)

tensor1 = tensor1.to(torch.complex64)
print(tensor1)
print(tensor1.dtype)

tensor1 = tensor1.to(torch.int32)
print(tensor1.dtype)




torch.int64
torch.float16
torch.float32
torch.float64
tensor([[1.+0.j, 2.+0.j],
        [2.+0.j, 3.+0.j],
        [3.+0.j, 4.+0.j]])
torch.complex64
torch.int32


# tensor和ndarray转换

In [5]:
# ndarray转tensor
array = np.array([1,2,3])
array[0] = 3 # 共享地址
tensor = torch.from_numpy(array)
print(tensor)

tensor([3, 2, 3])


In [45]:
# ndarray转tensor
array = np.array([1,2,3])
array[0] = 3 # 共享地址
tensor = torch.tensor(array)
print(tensor)

tensor([3, 2, 3])


In [8]:
# tensor转换成ndarray
tensor = torch.randint(0,10,[2,3])
print(tensor)
array = tensor.numpy()
tensor[:,1] = 2
print(array)
print(tensor)

tensor([[6, 7, 0],
        [5, 1, 7]])
[[6 2 0]
 [5 2 7]]
tensor([[6, 2, 0],
        [5, 2, 7]])


In [43]:
# 不共享内存
tensor = torch.randint(0,10,[2,3])
array = tensor.numpy().copy()
tensor[:,1] = 2
print(tensor)
print(array)

tensor([[8, 2, 3],
        [4, 2, 5]])
[[8 2 3]
 [4 6 5]]


In [44]:
array = np.array([1,2,3])
tensor = torch.from_numpy(array.copy())
array[2] = 5
print(array)
print(tensor)



[1 2 5]
tensor([1, 2, 3])


In [48]:
# tensor和标量转换
tensor = torch.tensor([10])
print(tensor)

print(tensor.item())


tensor([10])
10
