In [1]:
import torch
import numpy as np

# 创建张量

# 创建具体数张量

In [5]:
tensor1 = torch.tensor(10.8)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)
print()

tensor2 = torch.tensor([1,2,3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)
print()

tensor3 = torch.tensor([[1,2,3],[4,5,6]])
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)



tensor(10.8000)
torch.Size([])
torch.float32

tensor([1, 2, 3])
torch.Size([3])
torch.int64

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64



In [25]:
tensor = torch.tensor(np.array([[1,2,3],[4,5,6]]))
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


# 创建指定形状的张量

In [35]:
tensor = torch.Tensor(3,2,4)
print(tensor)
print(tensor.size())
print(tensor.dtype)

tensor([[[-1.4642e+17,  1.7825e-42,  2.3694e-38,  2.3694e-38],
         [ 2.3694e-38,  2.3694e-38,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [36]:
tensor = torch.Tensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.size())
print(tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


In [37]:
tensor = torch.Tensor(np.array([[1,2,3],[4,5,6]]))
print(tensor)
print(tensor.size())
print(tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


In [61]:
tensor = torch.Tensor(10)
print(tensor)
print(tensor.size())

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])


# 生成指定类型的张量

In [67]:
tensor = torch.FloatTensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.dtype)

tensor = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64


In [64]:
tensor = torch.IntTensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.int32


In [66]:
tensor = torch.tensor([[1,2,3],[4,5,6]],dtype = torch.int64)
print(tensor)
print(tensor.dtype)

tensor2 = torch.LongTensor([[1,2,3],[4,5,6]])
print(tensor2)
print(tensor2.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [68]:
tensor  = torch.BoolTensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.dtype)

tensor([[True, True, True],
        [True, True, True]])
torch.bool


# 创建指定区间的张量

In [80]:
tensor1 = torch.arange(0,1.5,0.6)
print(tensor1)

tensor2 = torch.arange(10,1,-1)
print(tensor2)

tensor([0.0000, 0.6000, 1.2000])
tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])


In [81]:
tensor = torch.linspace(0,4,4)
print(tensor)

tensor([0.0000, 1.3333, 2.6667, 4.0000])


In [4]:
tensor = torch.logspace(1,3,3,base = 10)
print(tensor)

tensor([  10.,  100., 1000.])


# 按数值填充张量

In [88]:
tensor = torch.full([2,3],5)
print(tensor)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [91]:
tensor = torch.zeros([2,3],dtype = torch.int32)
print(tensor)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [90]:
tensor = torch.ones([2,3])
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [92]:
tensor = torch.empty([2,3])
print(tensor)

tensor([[-1.4638e+17,  1.7825e-42,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00]])


In [100]:
tensor = torch.ones([2,3])
print(tensor)

tensor2 = torch.zeros_like(tensor)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 随机张量创建

In [101]:
# rand(size)：创建一个指定形状的随机张量，张量的元素取值范围是[0,1]
tensor  = torch.rand([2,3])
print(tensor)

tensor([[0.5649, 0.6497, 0.9520],
        [0.8808, 0.2632, 0.5366]])


In [128]:
tensor = torch.randint(0,10,[2,3])
print(tensor)

tensor2 = torch.randint_like(tensor,0,10)
print(tensor2)

tensor([[2, 4, 4],
        [7, 9, 4]])
torch.int64
tensor([[8, 9, 6],
        [5, 0, 1]])


In [120]:
# normal 正态分布
tensor = torch.randn([2,3])
print(tensor)

tensor([[ 0.1647,  0.3394,  0.1642],
        [-1.7262, -1.4394, -0.2961]])


In [121]:
tensor= torch.normal(mean = 0,std = 1,size = [2,3])
print(tensor)

tensor([[-0.3778, -0.5028,  0.3808],
        [ 1.4933, -0.1748,  0.7760]])
